return {
    blinds_enabled = true,
    boosters_enabled = true,
    decks_enabled = true,
    enhancements_enabled = true,
    card_enhancements_enabled = true,
    seals_enabled = true,
    jokers_enabled = true,
    tags_enabled = true,
    vouchers_enabled = true,
    resources_enabled = true,
    villager_enabled = true,
    health_enabled = true,
    xp_enabled = true,
    food_enabled = true,
    biomes_enabled = true,
    sheets_enabled = true,
    potions_enabled = true,
}
  