[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
G.FUNCS.discard_cards_from_highlighted = function(e, hook)
'''
position = 'after'
payload = '''
    if G.GAME.blind.name == 'bl_minecraft_drowned' and not G.GAME.blind.disabled then
        PB_UTIL.drowned_effect(e, hook)
        return
    end
'''
match_indent = true