-- Potion registry + card atlas. Mirrors content/foods/registry.lua and content/resources/registry.lua.
--
-- Each potion is one row in PB_UTIL.POTIONS, the single source of truth the ConsumableType loop
-- (potion_consumabletype.lua), the effect helpers (utilities/potions.lua), and the Brewing Stand
-- recipes (utilities/brewing.lua) all read.
--
-- Fields:
--   id      - key suffix; center is c_balacraft_potion_<id>; atlas + reference sprite use <id>.
--   name    - full display name (loc_txt). The short nameplate label is baked by gen_potion_cards.py.
--   kind    - 'drink' or 'throw' (throwables are Splash potions, brewed with Gunpowder).
--   when    - usage gate read by can_use: 'outside_blind' | 'inside_blind' | 'anytime'.
--   tier    - rarity weight for the Potion booster pack.
--   cost    - shop/pack price.
--   pos     - cell in bc_potion_cards (must match the grid in assets/gen_potion_cards.py).
--   mods    - which brew modifiers this potion accepts (drives brewing combos + loc text):
--             potency (Glowstone, both), duration (Redstone, drink-only), lingering (Dragon's Breath, throw-only).
--
-- Fire Resistance and Turtle Master are Phase 2 (they need new Nether-damage / game-speed
-- subsystems) and are intentionally absent here.

-- `pos` = the BASE (Level I, normal) cell. The card art atlas (bc_potion_cards, gen_potion_cards.py)
-- is a 4-col x 8-row grid: one ROW per potion (pos.y), four COLUMNS for the (Level, lasts-more)
-- combinations -- col = (potency and 2 or 0) + ((duration or lingering) and 1 or 0). The displayed
-- column is chosen per-card from the brew flags by the Card:set_sprites wrap in utilities/potions.lua.
PB_UTIL.POTIONS = {
    { id = 'swiftness',      name = 'Potion of Swiftness',      kind = 'drink', when = 'outside_blind', tier = 1, cost = 4, pos = { x = 0, y = 0 }, mods = { potency = true } },
    { id = 'strength',       name = 'Potion of Strength',       kind = 'drink', when = 'inside_blind',  tier = 2, cost = 5, pos = { x = 0, y = 1 }, mods = { potency = true, duration = true } },
    { id = 'instant_health', name = 'Potion of Instant Health', kind = 'drink', when = 'anytime',       tier = 2, cost = 5, pos = { x = 0, y = 2 }, mods = { potency = true } },
    { id = 'healing',        name = 'Potion of Healing',        kind = 'drink', when = 'anytime',       tier = 1, cost = 4, pos = { x = 0, y = 3 }, mods = { potency = true, duration = true } },
    { id = 'night_vision',   name = 'Potion of Night Vision',   kind = 'drink', when = 'inside_blind',  tier = 1, cost = 4, pos = { x = 0, y = 4 }, mods = { potency = true, duration = true } },
    { id = 'invisibility',   name = 'Potion of Invisibility',   kind = 'drink', when = 'inside_blind',  tier = 3, cost = 6, pos = { x = 0, y = 5 }, mods = { duration = true } },
    { id = 'poison',         name = 'Splash Potion of Poison',  kind = 'throw', when = 'inside_blind',  tier = 2, cost = 5, pos = { x = 0, y = 6 }, mods = { potency = true, lingering = true } },
    { id = 'harming',        name = 'Splash Potion of Harming', kind = 'throw', when = 'inside_blind',  tier = 3, cost = 6, pos = { x = 0, y = 7 }, mods = { potency = true, lingering = true } },
}

PB_UTIL.POTION_BY_ID = {}
for _, p in ipairs(PB_UTIL.POTIONS) do PB_UTIL.POTION_BY_ID[p.id] = p end

-- 71x95 cells, 3x3 grid (generated by assets/gen_potion_cards.py from assets/1x/potion_template.png).
PB_UTIL.potion_card_atlas = SMODS.Atlas {
    key = 'bc_potion_cards', path = 'potion_cards.png', px = 71, py = 95,
}

-- 34x34 tag-badge icons for the active-effects HUD (utilities/effects_ui.lua). One cell per
-- lasting effect, in EFFECT_HUD order (generated by assets/gen_effect_icons.py from the authentic
-- MC mob-effect textures in assets/reference/effects/).
PB_UTIL.effect_icon_atlas = SMODS.Atlas {
    key = 'bc_effect_icons', path = 'effect_icons.png', px = 34, py = 34,
}
