-- Active-effects HUD: a row of 34x34 tag-badge icons below the consumable area, one per
-- currently-active potion effect (utilities/potions.lua). Hover an icon -> a tooltip with the
-- effect's description and how many blinds it has left.
--
-- Read-only over state that already lives on G.GAME.balacraft.potion (the pstate table in
-- potions.lua): no new persisted state, no save/load code. Same lifecycle as the other BalaCraft
-- HUD bars (resource_ui / health_ui / hunger_ui / xp_ui): a Weak-bonded UIBox maintained by a
-- pcall'd Game:update driver, with a bc_major rebuild guard (Weak bonds are NOT auto-removed when
-- their major -- G.consumeables -- is recreated on a new run).
--
-- Only LASTING effects show (those with a live timer). Instant effects (Swiftness biome-switch,
-- base Instant Health) leave no state and never appear. Icons render left->right in EFFECT_HUD
-- order, so positions stay stable as effects come and go. The icon SHEET (bc_effect_icons) is
-- generated by assets/gen_effect_icons.py in this same order -- keep the two in sync.

local ICON_SZ  = 0.5    -- effect-icon sprite size in world-units (tunable)
local ICON_PAD = 0.06   -- padding around each icon cell
local ROW_DROP = 0.12   -- gap below the consumable area's bottom edge

-- Run states in which the HUD is interactive. Reuses resource_ui.lua's PANEL_STATES when that file
-- loaded (single source of truth), else a self-contained fallback (potions can be enabled without
-- the resources block). Resolved at runtime so load order never matters.
local HUD_STATES_FALLBACK = {
    [G.STATES.SELECTING_HAND] = true,
    [G.STATES.DRAW_TO_HAND]   = true,
    [G.STATES.HAND_PLAYED]    = true,
    [G.STATES.SHOP]           = true,
    [G.STATES.BLIND_SELECT]   = true,
    [G.STATES.ROUND_EVAL]     = true,
}

-- ---- Effect descriptors (order == bc_effect_icons columns == icon_pos.x) ----
-- remaining() returns the live timer (0 = inactive -> no icon). dur_text(n) phrases the tooltip's
-- duration line. desc supports localize colour codes ({C:attention}..{}).
local function pst()
    return G.GAME and G.GAME.balacraft and G.GAME.balacraft.potion or nil
end

local function blinds_left(n)
    return n .. ' blind' .. (n == 1 and '' or 's') .. ' left'
end

PB_UTIL.EFFECT_HUD = {
    { id = 'strength', title = 'Strength', icon_pos = { x = 0, y = 0 },
      desc = "Balance {C:attention}10%{} of {C:blue}Chips{} and {C:red}Mult{}",
      remaining = function() local s = pst(); return s and s.strength_blinds or 0 end,
      dur_text = blinds_left },
    { id = 'regeneration', title = 'Regeneration', icon_pos = { x = 1, y = 0 },
      desc = "Restores {C:red}hearts{} at the start of each blind",
      remaining = function() local s = pst(); return s and s.regen_blinds or 0 end,
      dur_text = blinds_left },
    { id = 'night_vision', title = 'Night Vision', icon_pos = { x = 2, y = 0 },
      desc = "Reveals the next cards you'll draw",
      remaining = function() local s = pst(); return s and s.nightvis_blinds or 0 end,
      dur_text = blinds_left },
    { id = 'invisibility', title = 'Invisibility', icon_pos = { x = 3, y = 0 },
      desc = "Take {C:attention}no damage{} from the boss blind",
      remaining = function() local s = pst(); return s and s.invis_blinds or 0 end,
      dur_text = blinds_left },
    { id = 'poison', title = 'Poison', icon_pos = { x = 4, y = 0 },
      desc = "Each hand or discard lowers the blind requirement",
      remaining = function() local s = pst(); return s and s.poison_blinds or 0 end,
      dur_text = blinds_left },
    { id = 'harming', title = 'Harming', icon_pos = { x = 5, y = 0 },
      desc = "Lowers the next blind's requirement",
      remaining = function() local s = pst(); return (s and s.harming_next_pct and s.harming_next_pct > 0) and 1 or 0 end,
      dur_text = function() return 'next blind' end },
}

-- Persistent live-bound duration strings (one per effect). The tooltip's duration row references
-- these by ref_table, so the count ticks down without rebuilding the UIBox.
PB_UTIL.effect_dur_refs = PB_UTIL.effect_dur_refs or {}
for _, e in ipairs(PB_UTIL.EFFECT_HUD) do
    PB_UTIL.effect_dur_refs[e.id] = PB_UTIL.effect_dur_refs[e.id] or { text = '' }
end

-- Resolve the registered icon atlas via its object key (the codebase convention; robust to any
-- key transformation). Nil until content/potions/registry.lua has loaded + injected it.
local function effect_atlas()
    local a = PB_UTIL.effect_icon_atlas
    return a and G.ASSET_ATLAS[a.key]
end

-- ---- UIBox definition ----
local function build_effect_row(active)
    local atlas = effect_atlas()
    local cells = {}
    for _, e in ipairs(active) do
        cells[#cells + 1] = {
            n = G.UIT.C,
            config = {
                align = 'cm', padding = ICON_PAD, r = 0.08, hover = true,
                tooltip = {
                    title = e.title,
                    text = { e.desc, { ref_table = PB_UTIL.effect_dur_refs[e.id], ref_value = 'text' } },
                },
            },
            nodes = { { n = G.UIT.O, config = { object = Sprite(0, 0, ICON_SZ, ICON_SZ, atlas, e.icon_pos) } } },
        }
    end
    return {
        n = G.UIT.ROOT, config = { align = 'cm', padding = 0, colour = G.C.CLEAR },
        nodes = { { n = G.UIT.R, config = { align = 'cm', padding = 0 }, nodes = cells } },
    }
end

-- ---- UIBox lifecycle ----
-- 'bm' = outer-bottom + horizontal-middle: the row's TOP edge lands ROW_DROP below the consumable
-- area's bottom edge, centred over it. Bonded 'Weak' to G.consumeables (the stable anchor there).
local function attach_effect_row(active, signature)
    if G.bc_effect_row and not G.bc_effect_row.REMOVED then G.bc_effect_row:remove() end
    G.bc_effect_row = UIBox {
        definition = build_effect_row(active),
        config = { align = 'bm', offset = { x = 0, y = ROW_DROP }, major = G.consumeables, bond = 'Weak' },
    }
    G.bc_effect_row.bc_major = G.consumeables
    G.bc_effect_row.bc_signature = signature
end

local function remove_effect_row()
    if G.bc_effect_row and not G.bc_effect_row.REMOVED then G.bc_effect_row:remove() end
    G.bc_effect_row = nil
end

-- ---- Per-frame driver ----
-- Gate on a normal run state + the atlas being ready. Refresh the live duration strings every
-- frame; rebuild the row ONLY when the SET of active effects changes (signature) or G.consumeables
-- was recreated. An empty set tears the row down.
function PB_UTIL.update_effect_row()
    local states = PB_UTIL.PANEL_STATES or HUD_STATES_FALLBACK
    local ok = G.STATE and states[G.STATE]
        and G.consumeables and G.GAME and G.GAME.balacraft and effect_atlas()
    if not ok then remove_effect_row(); return end

    local active, sig = {}, {}
    for _, e in ipairs(PB_UTIL.EFFECT_HUD) do
        local n = e.remaining() or 0
        if n > 0 then
            active[#active + 1] = e
            sig[#sig + 1] = e.id
            PB_UTIL.effect_dur_refs[e.id].text = e.dur_text(n)
        end
    end

    if #active == 0 then remove_effect_row(); return end

    local signature = table.concat(sig, ',')
    if not G.bc_effect_row or G.bc_effect_row.REMOVED
        or G.bc_effect_row.bc_signature ~= signature
        or G.bc_effect_row.bc_major ~= G.consumeables then
        attach_effect_row(active, signature)
    end
end

-- Single per-frame hook (pcall'd so a transient error can't wedge Game:update; composes with the
-- other HUD drivers' wraps).
local _game_update = Game.update
function Game:update(dt)
    _game_update(self, dt)
    local ok, err = pcall(PB_UTIL.update_effect_row)
    if not ok then sendDebugMessage('effect row error: ' .. tostring(err), 'BalaCraft') end
end
