-- Hunger HUD: a row of Minecraft drumsticks top-RIGHT, above the joker row -- mirroring the
-- hearts (top-left) for the classic MC HUD split. Same Weak-bonded-UIBox + Game:update driver
-- pattern as health_ui.lua; drumsticks auto-size to the right half of the joker width so the
-- two bars never overlap.

-- 9x9 cells (native MC haunch size; generated by assets/gen_hunger.py from the real
-- Minecraft hunger icons): full {0,0}, half {1,0}, empty {2,0}, saturated {3,0} (gold over-eat).
PB_UTIL.hunger_atlas = SMODS.Atlas { key = 'bc_hunger', path = 'hunger.png', px = 9, py = 9 }

PB_UTIL.HUNGER_STATES = {
    [G.STATES.SELECTING_HAND] = true,
    [G.STATES.DRAW_TO_HAND]   = true,
    [G.STATES.HAND_PLAYED]    = true,
    [G.STATES.SHOP]           = true,
    [G.STATES.BLIND_SELECT]   = true,
    [G.STATES.ROUND_EVAL]     = true,
}

local MAX_SZ    = 0.34
local SIDE_FRAC = 0.46    -- drumsticks occupy at most this fraction of the joker-row width
local ROW_GAP   = 0.12    -- match the hearts' gap so both rows align
local PAD       = 0.012

function PB_UTIL.build_hunger_bar()
    local hunger = PB_UTIL.get_hunger()
    local max_h  = PB_UTIL.get_max_hunger()
    local sticks = math.ceil(max_h / 2)                  -- 20 -> 10 drumsticks
    local sat_sticks = math.ceil(PB_UTIL.get_saturation() / 2)  -- gold drumsticks (banked over-eat)
    local atlas  = G.ASSET_ATLAS[PB_UTIL.hunger_atlas.key]
    local jok_w  = (G.jokers and G.jokers.T.w) or (5 * G.CARD_W)
    local sz = math.max(0.12, math.min(MAX_SZ, (jok_w * SIDE_FRAC) / sticks - 2 * PAD))

    local cells = {}
    for i = 1, sticks do
        -- Reverse the slot index so the LEFTMOST drumstick empties first -> hunger drains from
        -- the left (the rightmost stick, against the screen edge, is the last to go).
        local from_right = sticks - i                    -- 0 = rightmost slot
        local pos
        if from_right < sat_sticks then
            pos = { x = 3, y = 0 }                        -- gold: banked saturation fills from the right
        else
            local filled = hunger - from_right * 2
            pos = (filled >= 2 and { x = 0, y = 0 })
               or (filled == 1 and { x = 1, y = 0 })
               or { x = 2, y = 0 }
        end
        cells[#cells + 1] = {
            n = G.UIT.C, config = { align = 'cm', padding = PAD },
            nodes = {
                { n = G.UIT.O, config = { object = Sprite(0, 0, sz, sz, atlas, pos) } },
            },
        }
    end

    -- ROOT spans the joker width; inner row right-aligned ('cr') so drumsticks hug the RIGHT
    -- edge -> reads as "top-right, above the jokers" (mirror of the hearts' 'cl').
    return {
        n = G.UIT.ROOT,
        config = { align = 'cm', padding = 0, colour = G.C.CLEAR, minw = jok_w },
        -- Inner row spans the FULL joker width so 'cr' pushes the drumsticks to the right edge,
        -- mirroring the hearts' 'cl' left edge -> the Minecraft HUD split.
        nodes = { { n = G.UIT.R, config = { align = 'cr', padding = 0, minw = jok_w }, nodes = cells } },
    }
end

function PB_UTIL.attach_hunger_bar()
    local dropped = G.bc_hunger_bar and G.bc_hunger_bar.bc_hunger
        and (PB_UTIL.get_hunger() < G.bc_hunger_bar.bc_hunger)
    if G.bc_hunger_bar and not G.bc_hunger_bar.REMOVED then G.bc_hunger_bar:remove() end
    G.bc_hunger_bar = UIBox {
        definition = PB_UTIL.build_hunger_bar(),
        config = { align = 'tm', offset = { x = 0, y = -ROW_GAP }, major = G.jokers, bond = 'Weak' },
    }
    G.bc_hunger_bar.bc_major   = G.jokers
    G.bc_hunger_bar.bc_hunger  = PB_UTIL.get_hunger()
    G.bc_hunger_bar.bc_maxh    = PB_UTIL.get_max_hunger()
    G.bc_hunger_bar.bc_sat     = PB_UTIL.get_saturation()
    G.bc_hunger_bar.bc_w       = (G.jokers and G.jokers.T.w) or 0

    if dropped then
        pcall(function() G.bc_hunger_bar:juice_up(0.3, 0.15) end)
    end
end

local function remove_hunger_bar()
    if G.bc_hunger_bar and not G.bc_hunger_bar.REMOVED then G.bc_hunger_bar:remove() end
    G.bc_hunger_bar = nil
end

function PB_UTIL.update_hunger_bar()
    local active = G.STATE and PB_UTIL.HUNGER_STATES[G.STATE]
        and PB_UTIL.config and PB_UTIL.config.food_enabled
        and G.jokers and G.GAME and G.GAME.balacraft
        and PB_UTIL.hunger_atlas and G.ASSET_ATLAS[PB_UTIL.hunger_atlas.key]

    if not active then
        remove_hunger_bar()
        return
    end

    if not G.bc_hunger_bar or G.bc_hunger_bar.REMOVED
        or G.bc_hunger_bar.bc_major  ~= G.jokers
        or G.bc_hunger_bar.bc_hunger ~= PB_UTIL.get_hunger()
        or G.bc_hunger_bar.bc_maxh   ~= PB_UTIL.get_max_hunger()
        or G.bc_hunger_bar.bc_sat    ~= PB_UTIL.get_saturation()
        or G.bc_hunger_bar.bc_w      ~= ((G.jokers and G.jokers.T.w) or 0) then
        PB_UTIL.attach_hunger_bar()
    end
end

-- Own per-frame hook (stacks; pcall'd).
local _game_update = Game.update
function Game:update(dt)
    _game_update(self, dt)
    local ok, err = pcall(PB_UTIL.update_hunger_bar)
    if not ok then sendDebugMessage('hunger ui error: ' .. tostring(err), 'BalaCraft') end
end
