-- Biome registry (DATA ONLY -- logic lives in utilities/biomes.lua).
--
-- Mirrors the resource registry pattern (content/resources/registry.lua): a flat list
-- PB_UTIL.BIOMES plus a PB_UTIL.BIOME_BY_ID lookup. Each biome is the theme for ONE ante:
-- it tints the background, biases which ores drop, can add exclusive boss blinds, and can
-- apply a one-time modifier when you arrive.
--
-- Fields per biome:
--   id          unique string key (used in G.GAME.balacraft.current_biome)
--   name        display name
--   dimension   'overworld' | 'nether' | 'end'  (selection pools are dimension-isolated)
--   colour      HEX background tint (see utilities/biomes.lua -> ease_background_colour_blind wrap)
--   resource_bias { <ore id> = weight }  -- weights the drop roll WITHIN a tier (default weight 1)
--   mob_bias    { <mob drop id> = weight } -- weights the Night/Cave mob-loot roll (default 1);
--                                            use only where a real MC biome mob exists (Stray->Bone…)
--   on_enter    { dollars = n }          -- one-time modifier applied when the biome is chosen
--   bosses      { '<prefixed blind key>' } -- exclusive bosses (additive; gated by in_pool)
--   desc        short blurb lines for the selection card
--
-- VERTICAL SLICE: 4 Overworld biomes so the 3-choice screen (current excluded) has a real pool.
-- The full 16-biome set (8 Overworld + 4 Nether + 4 End) is documented in docs/biomes-and-dimensions.md.

-- Selection-card art atlas (tall 90x150 poster cells, one per biome; generated by
-- assets/gen_biomes.py). `pos.x` indexes the cell and MUST match gen_biomes.py's cell order.
PB_UTIL.biome_card_atlas = SMODS.Atlas {
    key = 'bc_biome_cards',
    path = 'biome_cards.png',
    px = 90,
    py = 150,
}

-- Deck-splash atlas for the per-Overworld-biome start-decks (71x95, one cell per biome at
-- pos.x = the biome's column; see content/decks/biome_decks.lua + assets/gen_biomes.py).
PB_UTIL.biome_deck_atlas = SMODS.Atlas {
    key = 'bc_biome_decks',
    path = 'biome_decks.png',
    px = 71,
    py = 95,
}

PB_UTIL.BIOMES = {
    {
        id = 'plains', name = 'Plains', dimension = 'overworld',
        colour = HEX('A0C46A'), pos = { x = 0, y = 0 },
        resource_bias = { wood = 3, cobblestone = 2 },
        desc = { 'Calm grasslands.', 'Wood & stone common.' },
    },
    {
        id = 'forest', name = 'Forest', dimension = 'overworld',
        colour = HEX('3F7D3A'), pos = { x = 1, y = 0 },
        resource_bias = { wood = 3, coal = 3 },
        bosses = { 'bl_balacraft_forest_guardian' },
        desc = { 'Dense woods.', 'Wood & coal favored.', 'A guardian lurks.' },
    },
    {
        id = 'desert', name = 'Desert', dimension = 'overworld',
        colour = HEX('E0C878'), pos = { x = 2, y = 0 },
        resource_bias = { gold = 3, iron = 2 },
        on_enter = { dollars = 4 },
        desc = { 'Harsh sands.', 'Gold & iron favored.', '+$4 on arrival.' },
    },
    {
        id = 'snowy_taiga', name = 'Snowy Taiga', dimension = 'overworld',
        colour = HEX('BFE3E0'), pos = { x = 3, y = 0 },
        resource_bias = { diamond = 3, iron = 2 },
        mob_bias = { bone = 3 },   -- Strays replace Skeletons in snowy biomes -> more Bone
        on_enter = { dollars = -2 },
        desc = { 'Frozen taiga.', 'Diamond & iron favored.', '-$2 to keep warm.' },
    },
    {
        id = 'jungle', name = 'Jungle', dimension = 'overworld',
        colour = HEX('2E7D32'), pos = { x = 4, y = 0 },
        resource_bias = { wood = 4, coal = 2 },
        desc = { 'Lush dense canopy.', 'Wood & coal abundant.' },
    },
    {
        id = 'swamp', name = 'Swamp', dimension = 'overworld',
        colour = HEX('5A6B47'), pos = { x = 5, y = 0 },
        resource_bias = { coal = 3, wood = 2 },
        mob_bias = { gunpowder = 2 },   -- Witches haunt swamp huts -> Gunpowder among their drops
        on_enter = { dollars = -1 },
        desc = { 'Murky wetlands.', 'Coal & wood favored.', '-$1, slow going.' },
    },
    {
        id = 'savanna', name = 'Savanna', dimension = 'overworld',
        colour = HEX('C9B458'), pos = { x = 6, y = 0 },
        resource_bias = { cobblestone = 3, gold = 2 },
        on_enter = { dollars = 2 },
        desc = { 'Dry acacia plains.', 'Stone & gold favored.', '+$2 caravan.' },
    },
    {
        id = 'badlands', name = 'Badlands', dimension = 'overworld',
        colour = HEX('B0542F'), pos = { x = 7, y = 0 },
        resource_bias = { gold = 4, iron = 2, redstone = 2 },
        on_enter = { dollars = 3 },
        desc = { 'Terracotta mesa.', 'Gold-rich & iron.', '+$3 prospecting.' },
    },
    -- Stronghold: a RITUAL-ONLY biome (ritual_only = true => excluded from every normal biome roll;
    -- see roll_biome_choices). It is offered ONLY as step 2 of the Eye-of-Ender trail (the marked
    -- option after the second Eye), the waypoint toward The End. pos = col 8 (assets/gen_biomes.py).
    {
        id = 'stronghold', name = 'Stronghold', dimension = 'overworld', ritual_only = true,
        colour = HEX('6E6A5A'), pos = { x = 8, y = 0 },
        resource_bias = { cobblestone = 3, redstone = 2 },
        desc = { 'Ancient stone halls.', 'The Eye points here.', 'The End portal waits.' },
    },

    -- --- Nether (reached via the Nether Portal voucher / Nether deck) ---
    -- Nether biomes bias the new tier-4 Netherite ore (registry + atlas now shipped).
    -- Quartz remains a future Nether-exclusive resource (not yet added).
    {
        id = 'nether_wastes', name = 'Nether Wastes', dimension = 'nether',
        colour = HEX('8C2A1E'), pos = { x = 0, y = 1 },
        resource_bias = { gold = 3, coal = 2, netherite = 2 },
        on_enter = { dollars = 3 },
        desc = { 'A sea of fire.', 'Gold & coal favored.', '+$3 plunder.' },
    },
    {
        id = 'crimson_forest', name = 'Crimson Forest', dimension = 'nether',
        colour = HEX('9C2632'), pos = { x = 1, y = 1 },
        resource_bias = { wood = 3, gold = 2, netherite = 2 },
        desc = { 'Crimson fungal woods.', 'Wood & gold favored.' },
    },
    {
        id = 'soul_sand_valley', name = 'Soul Sand Valley', dimension = 'nether',
        colour = HEX('3A565C'), pos = { x = 2, y = 1 },
        resource_bias = { coal = 3, iron = 2, netherite = 2 },
        on_enter = { dollars = -2 },
        desc = { 'Haunted teal flame.', 'Coal & iron favored.', '-$2, the souls drain you.' },
    },
    {
        id = 'basalt_deltas', name = 'Basalt Deltas', dimension = 'nether',
        colour = HEX('5E565E'), pos = { x = 3, y = 1 },
        resource_bias = { cobblestone = 2, diamond = 2, netherite = 3, redstone = 2 },
        bosses = { 'bl_balacraft_magma_lord' },
        desc = { 'Volcanic ash wastes.', 'Stone & diamond favored.', 'A magma lord rules.' },
    },

    -- --- The End (reached via the Eye-of-Ender trail; see utilities/biomes.lua) ---
    -- Collapsed to the SINGLE central island, matching Minecraft (the outer-island biomes were
    -- retired). Because the End dimension now holds only one biome, should_offer_biome_select stops
    -- offering further choices once you arrive -- you simply stay in The End. Keeps id 'central_end'
    -- (ender_sentinel's in_pool already targets it); only the display name changed to 'The End'.
    {
        id = 'central_end', name = 'The End', dimension = 'end',
        colour = HEX('2A2440'), pos = { x = 0, y = 2 },
        resource_bias = { diamond = 3, gold = 2 },
        bosses = { 'bl_balacraft_ender_sentinel' },
        desc = { 'The obsidian heart.', 'Diamond & gold favored.', 'A sentinel watches.' },
    },
}

-- id -> biome lookup (built once at load, same idiom as PB_UTIL.RESOURCE_BY_ID).
PB_UTIL.BIOME_BY_ID = {}
for _, b in ipairs(PB_UTIL.BIOMES) do
    PB_UTIL.BIOME_BY_ID[b.id] = b
end
