-- return {
--     descriptions = {
--         Blind = {
--             bl_minecraft_skeleton = {
--                 name = 'The Skeleton',
--                 text = { "destroy a random card in hand after playing poker hand" }
--             },
--             bl_minecraft_spider = {
--                 name = 'The Spider',
--                 text = { "disable all card enhancement" }
--             },
--             bl_minecraft_blaze = {
--                 name = 'The Blaze',
--                 text = { "After scoring, destroy a random card in hand" }
--             },
--             bl_minecraft_creeper = {
--                 name = 'The Creeper',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_minecraft_drowned = {
--                 name = 'The Drowned',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_minecraft_enderman = {
--                 name = 'The Enderman',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_minecraft_zombie = {
--                 name = 'The Zombie',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             }
--         }
--     }
-- } 