-- return {
--     descriptions = {
--         Blind = {
--             bl_balacraft_skeleton = {
--                 name = 'The Skeleton',
--                 text = { "destroy a random card in hand after playing poker hand" }
--             },
--             bl_balacraft_spider = {
--                 name = 'The Spider',
--                 text = { "disable all card enhancement" }
--             },
--             bl_balacraft_blaze = {
--                 name = 'The Blaze',
--                 text = { "After scoring, destroy a random card in hand" }
--             },
--             bl_balacraft_creeper = {
--                 name = 'The Creeper',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_balacraft_drowned = {
--                 name = 'The Drowned',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_balacraft_enderman = {
--                 name = 'The Enderman',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             },
--             bl_balacraft_zombie = {
--                 name = 'The Zombie',
--                 text = { 'destroy a random card in hand after playing poker hand' }
--             }
--         }
--     }
-- } 