-- Food registry + atlas. Mirrors content/resources/registry.lua.
-- `hunger` is in internal points (2 points = 1 drumstick), matching Minecraft's hunger
-- values (e.g. cooked porkchop = 8). `tier` drives food-pack rarity weighting.

PB_UTIL.FOODS = {
    { id = 'carrot',          name = 'Carrot',          tier = 1, hunger = 3, cost = 2, pos = { x = 0, y = 0 } },
    { id = 'potato',          name = 'Potato',          tier = 1, hunger = 1, cost = 2, pos = { x = 1, y = 0 } },
    { id = 'apple',           name = 'Apple',           tier = 1, hunger = 4, cost = 3, pos = { x = 2, y = 0 } },
    { id = 'baked_potato',    name = 'Baked Potato',    tier = 2, hunger = 5, cost = 4, pos = { x = 0, y = 1 } },
    { id = 'cooked_chicken',  name = 'Cooked Chicken',  tier = 2, hunger = 6, cost = 4, pos = { x = 1, y = 1 } },
    { id = 'cooked_porkchop', name = 'Cooked Porkchop', tier = 3, hunger = 8, cost = 6, pos = { x = 2, y = 1 } },
}

PB_UTIL.FOOD_BY_ID = {}
for _, f in ipairs(PB_UTIL.FOODS) do PB_UTIL.FOOD_BY_ID[f.id] = f end

-- 71x95 cells, 3x3 grid (generated by assets/gen_foods.py from assets/1x/Food_Template.png).
PB_UTIL.food_card_atlas = SMODS.Atlas {
    key = 'bc_food_cards', path = 'food_cards.png', px = 71, py = 95,
}

-- Small 34x34 food ICONS (frameless; assets/gen_food_icons.py) for the villager (Farmer) shop
-- offers -- icons, not scaled-down cards. 3 cols x 2 rows; a food's `pos` indexes this sheet.
PB_UTIL.food_icon_atlas = SMODS.Atlas {
    key = 'bc_food_icons', path = 'food_icons.png', px = 34, py = 34,
}
