-- Tool registry. 18 entries = 3 tools (sword/pickaxe/shovel) x 6 materials
-- (wood -> netherite). Mirrors content/foods/registry.lua: this file is pure DATA
-- (PB_UTIL.TOOLS) and defines no SMODS centers. It loads BEFORE content/resources/recipes.lua
-- (which reads PB_UTIL.TOOLS to build the 15 crafting recipes) -- see main.lua load order.
--
-- ART: all 18 tools share ONE hand-styled card sheet, bc_tools / assets/tools.png (generated by
-- assets/gen_tool_cards.py). Each tool's cell is { x = durability frame, y = atlas_row } -- see
-- tool_consumabletype.lua. The `pos` field below (material cell on bc_resource_cards) is now
-- vestigial for tool art; kept only as legacy data.

-- Per-material metadata. `tier` (1..6) indexes the per-tool value/cost tables below.
-- `pos` is the material's cell on bc_resource_cards. 'cobblestone' is the Stone tier.
local MATERIALS = {
    { id = 'wood',        adj = 'Wooden',  tier = 1, pos = { x = 0, y = 0 } },
    { id = 'cobblestone', adj = 'Stone',   tier = 2, pos = { x = 1, y = 0 } },
    { id = 'iron',        adj = 'Iron',    tier = 3, pos = { x = 0, y = 1 } },
    { id = 'gold',        adj = 'Golden',  tier = 4, pos = { x = 1, y = 1 } },
    { id = 'diamond',     adj = 'Diamond', tier = 5, pos = { x = 2, y = 1 } },
    { id = 'netherite',   adj = 'Netherite', tier = 6, pos = { x = 2, y = 2 } },
}

-- Per-tool noun + the value per tier (1..5) + sell/cost per tier.
--   sword  -> X-Mult for the rest of the blind (diamond/netherite: Mult exponent, see tool_consumabletype)
--   pickaxe-> +N of a random ore on the next blind defeated
--   shovel -> CHANCE to find +$N on the next blind defeated (a gamble; Fortune raises the odds)
local TOOL_SPECS = {
    { tool = 'sword',   noun = 'Sword',   values = { 1.25, 1.5, 2, 4, 8, 16 } },
    { tool = 'pickaxe', noun = 'Pickaxe', values = { 1, 2, 3, 4, 5, 6 } },
    -- Shovel toned down from {1,2,3,5,10,15}: a top shovel was guaranteed +$15, a no-brainer.
    -- Now caps at $6 AND only pays on a successful dig roll (PB_UTIL.shovel_find_chance).
    { tool = 'shovel',  noun = 'Shovel',  values = { 1, 2, 3, 4, 5, 6 } },
}
local COST_BY_TIER = { 3, 4, 5, 6, 8, 10 }

-- Durability: base number of USES a tool gets before it breaks (one use per blind).
-- Keyed by material id. Tougher materials last longer; note gold == iron by design.
-- The Durability enchantment multiplies these (see content/enhancements/).
local BASE_USES = { wood = 1, cobblestone = 2, iron = 3, gold = 3, diamond = 4, netherite = 5 }

PB_UTIL.TOOLS = {}
for _, spec in ipairs(TOOL_SPECS) do
    for _, m in ipairs(MATERIALS) do
        PB_UTIL.TOOLS[#PB_UTIL.TOOLS + 1] = {
            id        = spec.tool .. '_' .. m.id,    -- 'sword_diamond'
            tool      = spec.tool,                   -- 'sword' | 'pickaxe' | 'shovel'
            material  = m.id,                        -- 'wood' .. 'netherite'
            name      = m.adj .. ' ' .. spec.noun,   -- 'Diamond Sword'
            tier      = m.tier,                      -- 1..6 (material tier)
            value     = spec.values[m.tier],         -- X-mult / ore count / dollars
            cost      = COST_BY_TIER[m.tier],
            pos       = m.pos,                        -- placeholder material cell
            base_uses = BASE_USES[m.id],             -- durability budget (uses before breaking)
            -- 0-based row, shared by BOTH the base card sheet (bc_tools) and the enchant atlas
            -- (bc_tool_cards): stable build order (swords, then pickaxes, then shovels; 6
            -- materials each) => 0..17.
            atlas_row = #PB_UTIL.TOOLS,
        }
    end
end

PB_UTIL.TOOL_BY_ID = {}
for _, t in ipairs(PB_UTIL.TOOLS) do PB_UTIL.TOOL_BY_ID[t.id] = t end
