-- Tool consumable type + the 24 tool cards (4 tools: sword/pickaxe/shovel/axe x 6 materials).
-- Tools are CRAFT-ONLY (shop_rate = 0) but DO appear in the collection (no_collection = false).
--
-- PERSISTENT, MULTI-USE items (not single-use): each tool has a durability budget
-- (ability.extra.uses_left/max_uses, base by material in registry.lua). Using a tool always
-- spends one durability use; at 0 uses it breaks (start_dissolve). keep_on_use=true stops the
-- engine from auto-consuming it. Per-tool state lives on card.ability.extra (deep-copied per
-- card, serialized natively -- no custom save/load).
--   Once-per-blind lock: the sword, the shovel and the axe-as-WEAPON set used_this_blind and a
--   per-type lock so only one of each can act per blind. MINING actions are exempt and MULTI-USE
--   per blind -- the pickaxe (always) and the axe when chopping highlighted wood (is_mine_mode):
--   they still spend durability but never take the locks, so you can keep mining/chopping all blind.
--
-- Each card's use() writes per-blind / pending state onto G.GAME.balacraft (seeded in the
-- init_game_object wrapper in utilities/resources.lua):
--   sword   -> lower tiers (wood..gold) multiply G.GAME.balacraft.sword_xmult (flat X-Mult);
--              TOP tiers (diamond/netherite) instead add to G.GAME.balacraft.sword_exp, which
--              RAISES the hand Mult to a power during scoring (Talisman-safe) so they keep pace
--              with super-exponential late-game scores. Both applied via the lovely.toml patch,
--              reset each blind via reset_game_globals. Sharpness scales the X-mult on flat
--              swords, and deepens the exponent on top-tier swords.
--   pickaxe -> mines the Ore-Block cards highlighted in hand when Used, gated by the material's
--              mining level (PB_UTIL.can_mine); Fortune adds a random 0..tier bonus to each yield.
--   shovel  -> arms G.GAME.balacraft.pending_shovel  (+$N on next blind defeated)
--              Fortune enchant raises the shovel's find odds.
--   axe     -> DUAL. With WOOD ore-block(s) highlighted: chops +`value` wood per card (may take
--              several at once). Used ALONE (no wood selected): a WEAPON -- arms the hybrid
--              axe_chips + axe_xmult buff for this blind (lovely.toml scoring patch).
--   The pickaxe/axe read G.hand.highlighted in use() (the same UX as applying a Tarot to selected
--   cards), so no extra UI is needed. PB_UTIL.oreblock_ore / can_mine / revert_oreblock_card come
--   from utilities/card_enhancements.lua + content/resources/registry.lua (guarded if absent).
-- The pending one-shots are consumed in PB_UTIL.grant_blind_drop (Blind:defeat wrapper).
-- Enchant math helpers (PB_UTIL.sharpness_mult / fortune_bonus) load with content/enhancements/
-- and are guarded here so tools still work when enhancements_enabled is off.
--
-- Depends on: PB_UTIL.TOOLS (content/tools/registry.lua) and the bc_resource_cards atlas
-- (content/resources/registry.lua) -- both load before this file (see main.lua).

-- Hand-drawn tool card art. All 24 tool cards (4 tools x 6 materials) are full 71x95 card faces
-- generated by assets/gen_tool_cards.py (template = the hand-made wood_sword.png + the bold tarot
-- alphabet + Minecraft tool sprites), baked into ONE combined sheet `tools.png` (assets/1x + 2x):
--   ROW    = the tool's atlas_row (registry.lua): swords 0..5, pickaxes 6..11, shovels 12..17, axes 18..23.
--   COLUMN = durability frame, 0 = full bar/green .. 10 = empty/red (update_durability_frame picks it).
-- Note the Stone tier's material id is 'cobblestone'.
SMODS.Atlas { key = 'bc_tools', path = 'tools.png', px = 71, py = 95 }

-- Small 34x34 tag-badge icons for the crafting recipe list / output preview (assets/gen_tool_icons.py).
-- 6 cols (material: wood, cobblestone, iron, gold, diamond, netherite) x 4 rows (tool: sword, pickaxe,
-- shovel, axe). The per-tool icon_pos below MUST match that grid order.
PB_UTIL.tool_icon_atlas = SMODS.Atlas { key = 'bc_tool_icons', path = 'tool_icons.png', px = 34, py = 34 }

-- icon_pos = cell in bc_tool_icons (crafting recipe list / output preview). The card art itself is
-- the shared bc_tools atlas, row = the tool's atlas_row (set on the Consumable's pos below).
local ART = {
    sword_wood          = { icon_pos = { x = 0, y = 0 } },
    sword_cobblestone   = { icon_pos = { x = 1, y = 0 } },
    sword_iron          = { icon_pos = { x = 2, y = 0 } },
    sword_gold          = { icon_pos = { x = 3, y = 0 } },
    sword_diamond       = { icon_pos = { x = 4, y = 0 } },
    sword_netherite     = { icon_pos = { x = 5, y = 0 } },
    pickaxe_wood        = { icon_pos = { x = 0, y = 1 } },
    pickaxe_cobblestone = { icon_pos = { x = 1, y = 1 } },
    pickaxe_iron        = { icon_pos = { x = 2, y = 1 } },
    pickaxe_gold        = { icon_pos = { x = 3, y = 1 } },
    pickaxe_diamond     = { icon_pos = { x = 4, y = 1 } },
    pickaxe_netherite   = { icon_pos = { x = 5, y = 1 } },
    shovel_wood         = { icon_pos = { x = 0, y = 2 } },
    shovel_cobblestone  = { icon_pos = { x = 1, y = 2 } },
    shovel_iron         = { icon_pos = { x = 2, y = 2 } },
    shovel_gold         = { icon_pos = { x = 3, y = 2 } },
    shovel_diamond      = { icon_pos = { x = 4, y = 2 } },
    shovel_netherite    = { icon_pos = { x = 5, y = 2 } },
    -- Rows 3-4 of bc_tool_icons are the non-tool EXTRAS (torch/bow/fishing_rod/crossbow/arrow/
    -- bone_meal on row 3; tnt/firework on row 4 -- see assets/gen_tool_icons.py). Axes take the
    -- next fully-free row, 5.
    axe_wood            = { icon_pos = { x = 0, y = 5 } },
    axe_cobblestone     = { icon_pos = { x = 1, y = 5 } },
    axe_iron            = { icon_pos = { x = 2, y = 5 } },
    axe_gold            = { icon_pos = { x = 3, y = 5 } },
    axe_diamond         = { icon_pos = { x = 4, y = 5 } },
    axe_netherite       = { icon_pos = { x = 5, y = 5 } },
}

-- center key -> badge cell in bc_tool_icons, for the crafting recipe list & output preview
-- (crafting_ui.lua). Non-tool consumables (e.g. Torch) are absent and fall back to card art.
PB_UTIL.tool_icon_pos = {}
for id, a in pairs(ART) do
    if a.icon_pos then PB_UTIL.tool_icon_pos['c_balacraft_tool_' .. id] = a.icon_pos end
end

-- ===== Durability bar via baked sprite frames ======================================
-- Balatro applies each card's 3D parallax/tilt inside the card SHADER (Card:draw ->
-- :draw_shader, cursor-driven tilt_var), NOT in the draw geometry -- so a hand-drawn
-- love.graphics overlay can never follow the card (it drifts with screen position).
-- Instead every tool's art is its ROW in the combined bc_tools sheet -- NFRAMES durability
-- columns (col 0 = full/green ... col NFRAMES-1 = empty/red); we pick the column each tick
-- from uses_left/max_uses by swapping the center sprite's cell (keeping the tool's row). That
-- cell is the real card sprite, so it goes through the shader and tilts perfectly.
-- NFRAMES and the column ordering MUST match assets/gen_tool_cards.py.
local NFRAMES = 11

-- The tool's 0-based row in bc_tools (== registry atlas_row), from the card's center key.
-- PB_UTIL.TOOL_BY_ID always exists here (content/tools/registry.lua loads first).
local function tool_atlas_row(card)
    local key = card.config and card.config.center and card.config.center.key
    local id  = key and key:match('^c_balacraft_tool_(.+)$')
    local t   = id and PB_UTIL.TOOL_BY_ID and PB_UTIL.TOOL_BY_ID[id]
    return (t and t.atlas_row) or 0
end

local function update_durability_frame(self, card, dt)
    local cen = card.children and card.children.center
    if not cen or not cen.set_sprite_pos then return end
    -- Don't fight the enchanted-tool sprite: enchanting.lua swaps the center onto the enchant atlas
    -- (balacraft_bc_tool_cards). SMODS prefixes atlas keys, so resolve it via the registered object's
    -- key -- the old bare 'bc_tools' literal returned nil, so this guard never fired and durability
    -- would clobber the enchant cell's x (frame) every frame. When on the enchant atlas, leave it.
    local ench_atlas = PB_UTIL.tool_atlas and G.ASSET_ATLAS and G.ASSET_ATLAS[PB_UTIL.tool_atlas.key]
    if ench_atlas and cen.atlas == ench_atlas then return end
    local e = card.ability and card.ability.extra
    local frac = 1                                   -- default full (collection / no durability yet)
    if e and (e.max_uses or 0) > 0 then
        frac = math.max(0, math.min(1, (e.uses_left or e.max_uses) / e.max_uses))
    end
    local frame = math.floor((1 - frac) * (NFRAMES - 1) + 0.5)   -- 0 = full, NFRAMES-1 = empty
    local row = tool_atlas_row(card)
    if cen.sprite_pos and (cen.sprite_pos.x ~= frame or cen.sprite_pos.y ~= row) then
        cen:set_sprite_pos({ x = frame, y = row })
    end
end

SMODS.ConsumableType {
    key = 'balacraft_tool',
    primary_colour = HEX('7f8c8d'),
    secondary_colour = HEX('bdc3c7'),
    collection_rows = { 6, 6 },        -- 2 rows of six per page (was 4 -- the modal ran too tall).
                                       -- 29 cards (24 tools + torch/firework/bone_meal/arrow/tnt)
                                       -- now paginate sword+pickaxe / shovel+axe / extras.
    shop_rate = 0,                     -- craft-only; never rolls in the shop
    no_collection = false,             -- but DO list them in the collection
    default = 'c_balacraft_tool_sword_wood',
    -- Picking a tool/Torch from a Toolbox pack ADDS it to the consumable area to use later
    -- (gated on having room), instead of using it on the spot. Without this, the pack falls
    -- through to the default consumable path and calls use_consumeable immediately -- but a
    -- tool's can_use needs SELECTING_HAND, so the pick would be wasted in the pack. SMODS reads
    -- select_card in card_select_area -> use_card sets select_to = 'consumeables' and emplaces
    -- the card there. The Torch rides this type too, so it also gets the take-and-hold behaviour.
    select_card = 'consumeables',
    loc_txt = { name = 'Tool', collection = 'Tools' },
}

-- Top-tier swords (by material) scale by an EXPONENT on the hand Mult instead of a flat X-Mult.
-- The value is the bonus ADDED above 1, so the applied power = 1 + bonus (diamond Mult^1.25,
-- netherite Mult^1.5). Tunable. Any sword material not listed here keeps its flat X-Mult.
local SWORD_EXP_BONUS = { diamond = 0.25, netherite = 0.5 }
local SHARPNESS_EXP_STEP = 0.05   -- Sharpness deepens an exponent sword by this much per tier

-- Static tooltip text per tool: the effect (tier value baked in) + the live durability line
-- (#1#/#2# = uses left / max, filled by loc_vars). Applied enchantments are NOT here -- they
-- are appended dynamically in loc_vars (main_end), one short line each, only when present.
local function tool_text(t)
    local body
    if t.tool == 'sword' then
        local exp_bonus = SWORD_EXP_BONUS[t.material]
        if exp_bonus then
            body = {
                'Raise Mult to the {X:mult,C:white}^' .. (1 + exp_bonus) .. '{} power',
                'on every hand for the rest of this {C:attention}Blind{}.',
            }
        else
            body = {
                '{X:mult,C:white}X' .. t.value .. '{} Mult on every hand',
                'for the rest of this {C:attention}Blind{}.',
            }
        end
    elseif t.tool == 'pickaxe' then
        body = {
            'Highlight {C:attention}Ore Block{} cards in hand,',
            'then Use to {C:attention}mine{} the ones this',
            'pickaxe tier can break.',
        }
    elseif t.tool == 'axe' then
        body = {
            'On {C:attention}Wood{}: chop {C:attention}+' .. t.value .. '{} wood per card.',
            'Alone: a {C:attention}weapon{} -- {C:blue}+' .. (t.weapon_chips or 0) .. '{} Chips',
            'and {X:mult,C:white}X' .. (t.weapon_xmult or 1) .. '{} Mult this {C:attention}Blind{}.',
        }
    else -- shovel
        body = {
            '{C:green}Dig{}: ~50% chance to find',
            '{C:money}$' .. t.value .. '{} on the next blind defeated.',
        }
    end
    body[#body + 1] = '{C:green}Uses #1#/#2#{} {C:inactive}(1/Blind)'
    return body
end

-- Enchant effect values mirrored here so tools don't depend on the enhancements registry being
-- loaded. Used to build the dynamic per-enchant tooltip lines.
local TIER_LABEL      = { 'I', 'II', 'III' }
local SHARPNESS_MULT  = { 1.25, 1.5, 1.75 }   -- sword X-mult multiplier (Sharpness)
local DURABILITY_MULT = { 1.25, 1.5, 2 }      -- max-uses multiplier
local FORTUNE_MAX     = { 1, 2, 3 }           -- max bonus loot (random 0..max)

-- One description row: "<Name Tier>  <short effect>". Name is coloured; the effect uses the
-- description box's default DARK text (the box has a light background, so white is invisible).
local function ench_row(name, name_colour, effect)
    return { n = G.UIT.R, config = { align = 'cm', padding = 0.02 }, nodes = {
        { n = G.UIT.T, config = { text = name .. ' ', colour = name_colour, scale = 0.30 } },
        { n = G.UIT.T, config = { text = effect, colour = G.C.UI.TEXT_DARK, scale = 0.30 } },
    } }
end

-- ===== Mining (pickaxe + axe) =======================================================
-- All driven from the tool's use() reading G.hand.highlighted -- the same UX as applying a Tarot
-- to selected cards. The ore-block helpers live in utilities/card_enhancements.lua (loaded later,
-- under card_enhancements_enabled) and PB_UTIL.can_mine in content/resources/registry.lua, so every
-- call is guarded -- mining is simply a no-op when ore blocks are disabled.

-- A live (un-mined) ore-block id for a highlighted hand card, or nil.
local function fresh_oreblock(c)
    if not PB_UTIL.oreblock_ore then return nil end
    if c.ability and c.ability.extra and c.ability.extra._mined then return nil end
    return PB_UTIL.oreblock_ore(c)
end

-- Grant `amount` of `ore` from card `c`: mark mined, pop the "+N Ore" text, revert to a base card.
local function take_ore(c, ore, amount)
    if PB_UTIL.add_resource then PB_UTIL.add_resource(ore, amount) end
    c.ability.extra = c.ability.extra or {}
    c.ability.extra._mined = true
    local res = PB_UTIL.RESOURCE_BY_ID and PB_UTIL.RESOURCE_BY_ID[ore]
    card_eval_status_text(c, 'extra', nil, nil, nil,
        { message = '+' .. amount .. ' ' .. ((res and res.name) or ore), colour = G.C.GOLD })
    if PB_UTIL.revert_oreblock_card then PB_UTIL.revert_oreblock_card(c, 0.4) end
end

-- How many fresh WOOD ore-blocks are highlighted (decides axe weapon-vs-chop mode).
local function highlighted_wood_count()
    local hand = G.hand and G.hand.highlighted
    if not hand then return 0 end
    local n = 0
    for _, c in ipairs(hand) do if fresh_oreblock(c) == 'wood' then n = n + 1 end end
    return n
end

-- True when this Use is a MINING action: the pickaxe (always mines) or the axe while wood is
-- highlighted (chopping). Mining actions are multi-use per blind -- they spend durability but
-- skip the once-per-blind locks. NB: evaluate this BEFORE acting, since take_ore reverts the
-- highlighted ore-blocks (so highlighted_wood_count would read 0 afterwards).
local function is_mine_mode(t)
    if t.tool == 'pickaxe' then return true end
    if t.tool == 'axe' then return highlighted_wood_count() > 0 end
    return false
end

-- Pickaxe: mine every highlighted ore-block this tier can break. Wood is rejected (use an Axe),
-- too-hard ores flash "Need a better pickaxe". Yields 1 + Fortune each. Returns true iff anything
-- was actually mined (so a wasted click -- nothing valid selected -- does NOT spend a use).
local function mine_with_pickaxe(tool_card, t)
    local hand = G.hand and G.hand.highlighted
    local level = t.mining_level or 0
    local ench  = (tool_card.ability and tool_card.ability.extra and tool_card.ability.extra.enchants) or {}
    local mined_any = false
    if hand then
        for _, c in ipairs(hand) do
            local ore = fresh_oreblock(c)
            if ore then
                if ore == 'wood' then
                    card_eval_status_text(c, 'extra', nil, nil, nil,
                        { message = 'Use an Axe', colour = G.C.UI.TEXT_INACTIVE })
                elseif PB_UTIL.can_mine and PB_UTIL.can_mine(level, ore) then
                    local fb = (PB_UTIL.fortune_bonus and PB_UTIL.fortune_bonus(ench.fortune or 0, c)) or 0
                    take_ore(c, ore, 1 + fb)
                    mined_any = true
                else
                    card_eval_status_text(c, 'extra', nil, nil, nil,
                        { message = 'Need a better pickaxe', colour = G.C.RED })
                end
            end
        end
    end
    if not mined_any then
        card_eval_status_text(tool_card, 'extra', nil, nil, nil,
            { message = 'Select an Ore Block', colour = G.C.UI.TEXT_INACTIVE })
    end
    return mined_any
end

-- Axe wood-chop: harvest +`t.value` wood from each highlighted wood ore-block. Returns true iff
-- any wood was chopped (caller only enters this path when wood is selected, so it normally does).
local function chop_wood_with_axe(t)
    local hand = G.hand and G.hand.highlighted
    if not hand then return false end
    local per = t.value or 1
    local got = false
    for _, c in ipairs(hand) do
        if fresh_oreblock(c) == 'wood' then
            take_ore(c, 'wood', per)
            got = true
        end
    end
    return got
end

for _, tool in ipairs(PB_UTIL.TOOLS) do
    local t = tool
    SMODS.Consumable {
        key = 'tool_' .. t.id,              -- => c_balacraft_tool_sword_wood, ...
        set = 'balacraft_tool',
        atlas = 'bc_tools',                  -- shared combined tool-card sheet (all 18 tools)
        pos = { x = 0, y = t.atlas_row },     -- row = this tool; col 0 = full durability
        cost = t.cost,
        discovered = true,
        loc_txt = { name = t.name, text = tool_text(t) },
        update = update_durability_frame,   -- swap the baked durability frame from uses_left/max_uses

        -- Per-tool durability + enchant state. copy_table'd onto each card's ability.extra
        -- (deep copy, so every card gets its own `enchants` table), and serialized natively
        -- by Card:save/load -- no custom save/load (the mod's load-bearing convention).
        config = { extra = {
            uses_left       = t.base_uses,  -- durability budget; tool breaks at 0
            max_uses        = t.base_uses,  -- raised by the Durability enchant
            used_this_blind = false,        -- reset each blind in resources.lua
            enchants        = { sharpness = 0, durability = 0, fortune = 0 },
        } },

        -- #1#/#2# = uses left/max for the static text. Applied enchantments are appended as
        -- one short line each via main_end (nothing shown for enchants the tool doesn't have).
        loc_vars = function(self, info_queue, card)
            local e  = (card and card.ability and card.ability.extra) or {}
            local en = e.enchants or {}
            local s, d, f = en.sharpness or 0, en.durability or 0, en.fortune or 0
            local rows = {}
            if t.tool == 'sword' and s >= 1 then
                local sharp_effect
                if SWORD_EXP_BONUS[t.material] then
                    sharp_effect = '+' .. (SHARPNESS_EXP_STEP * s) .. ' exponent'
                else
                    sharp_effect = 'X' .. SHARPNESS_MULT[s] .. ' Mult'
                end
                rows[#rows + 1] = ench_row('Sharpness ' .. (TIER_LABEL[s] or s), G.C.FILTER, sharp_effect)
            end
            if t.tool == 'pickaxe' and f >= 1 then
                rows[#rows + 1] = ench_row('Fortune ' .. (TIER_LABEL[f] or f), G.C.BLUE, 'up to +' .. FORTUNE_MAX[f] .. ' loot')
            elseif t.tool == 'shovel' and f >= 1 then
                rows[#rows + 1] = ench_row('Fortune ' .. (TIER_LABEL[f] or f), G.C.BLUE, '+' .. (15 * f) .. '% find odds')
            end
            if d >= 1 then
                rows[#rows + 1] = ench_row('Durability ' .. (TIER_LABEL[d] or d), G.C.GREEN, 'X' .. DURABILITY_MULT[d] .. ' Uses')
            end
            local res = { vars = { e.uses_left or t.base_uses, e.max_uses or t.base_uses } }
            if rows[1] then
                res.main_end = { { n = G.UIT.C, config = { align = 'cm', padding = 0.02 }, nodes = rows } }
            end
            return res
        end,

        -- Persistent: never auto-consumed by use_card. We destroy it ourselves when it breaks.
        keep_on_use = function(self, card)
            return true
        end,

        -- Usable only while selecting a hand and only if it has uses left. Mining actions
        -- (pickaxe, or axe with wood highlighted) are MULTI-USE per blind -- they skip the
        -- locks below. For the sword/shovel/axe-as-weapon it's once per blind, PER TYPE: if
        -- one of this kind already acted this blind (tool_type_used[t.tool]) the rest are
        -- blocked (you can still mix one of each type); the per-card used_this_blind also
        -- blocks re-using this same card.
        can_use = function(self, card)
            local e = card.ability and card.ability.extra
            if not e or (e.uses_left or 0) <= 0 then return false end
            if G.STATE ~= G.STATES.SELECTING_HAND then return false end
            if not is_mine_mode(t) then
                if e.used_this_blind then return false end
                local bc = G.GAME and G.GAME.balacraft
                if bc and bc.tool_type_used and bc.tool_type_used[t.tool] then return false end
            end
            return true
        end,

        use = function(self, card, area, copier)
            local bc = G.GAME and G.GAME.balacraft
            local e  = card.ability and card.ability.extra
            if not bc or not e then return end
            local ench = e.enchants or {}
            -- Capture the mode BEFORE acting: mining reverts the highlighted ore-blocks, so for the
            -- axe `is_mine_mode` (which reads the highlight) must be sampled now. Drives both the
            -- axe chop-vs-weapon branch and the once-per-blind lock below.
            local mine_mode = is_mine_mode(t)
            -- Whether the use actually DID something. Mining a no-op selection (no valid ore) leaves
            -- this false so the click doesn't waste a durability use / lock the tool for the blind.
            local did_act = true

            if t.tool == 'sword' then
                local exp_bonus = SWORD_EXP_BONUS[t.material]
                if exp_bonus then
                    -- Top-tier sword: scale by raising the hand Mult to a power (Talisman-safe),
                    -- so it grows with the score instead of a now-trivial flat Xmult. Sharpness
                    -- DEEPENS the exponent rather than multiplying a flat Xmult.
                    local sh = ench.sharpness or 0
                    if sh >= 1 then exp_bonus = exp_bonus + SHARPNESS_EXP_STEP * sh end
                    bc.sword_exp = (bc.sword_exp or 1) + exp_bonus
                else
                    -- Lower-tier sword: flat Xmult; Sharpness multiplies it (x1 when off).
                    local sm = (PB_UTIL.sharpness_mult and PB_UTIL.sharpness_mult(ench.sharpness or 0)) or 1
                    bc.sword_xmult = (bc.sword_xmult or 1) * (t.value * sm)
                end
            elseif t.tool == 'pickaxe' then
                -- Mine the highlighted ore-block cards this tier can break (1 + Fortune each).
                did_act = mine_with_pickaxe(card, t)
            elseif t.tool == 'axe' then
                if mine_mode then
                    -- Wood selected -> chop it (more than bare hand, scaled by tier; multi-card).
                    did_act = chop_wood_with_axe(t)
                else
                    -- No wood selected -> WEAPON: hybrid +Chips AND xMult this blind (lovely.toml
                    -- scoring patch applies them; PB_UTIL.axe_score_message pops the juice).
                    bc.axe_chips = (bc.axe_chips or 0) + (t.weapon_chips or 0)
                    bc.axe_xmult = (bc.axe_xmult or 1) * (t.weapon_xmult or 1)
                    card_eval_status_text(card, 'extra', nil, nil, nil,
                        { message = 'Axe readied!', colour = G.C.RED })
                end
            else -- shovel: a GAMBLE. Roll the dig; pay the full tier value on a hit, nothing on a
                -- miss. Fortune raises the odds (not the loot). Payout lands on the next Blind:defeat.
                local chance = (PB_UTIL.shovel_find_chance and PB_UTIL.shovel_find_chance(ench.fortune or 0)) or 0.5
                local hit = pseudorandom(pseudoseed('bc_shovel_' .. tostring(card.sort_id or 'x'))) < chance
                if hit then
                    bc.pending_shovel = (bc.pending_shovel or 0) + t.value
                    card_eval_status_text(card, 'extra', nil, nil, nil,
                        { message = 'Found $' .. t.value .. '!', colour = G.C.MONEY, sound = 'coin3' })
                else
                    card_eval_status_text(card, 'extra', nil, nil, nil,
                        { message = 'Nothing...', colour = G.C.UI.TEXT_INACTIVE, sound = 'cancel' })
                end
            end

            -- A no-op mining click (nothing valid selected) doesn't lock or spend the tool.
            if not did_act then return end

            -- Mining actions (pickaxe / axe chopping wood) are multi-use per blind: spend a
            -- durability use but DON'T take the locks. Sword / shovel / axe-as-weapon set the
            -- once-per-blind lock (this card) + the per-TYPE lock (blocks other tools of the
            -- same kind this blind).
            if not mine_mode then
                e.used_this_blind = true
                bc.tool_type_used = bc.tool_type_used or {}
                bc.tool_type_used[t.tool] = true
            end
            e.uses_left = (e.uses_left or 1) - 1
            if e.uses_left <= 0 then
                -- Break. Defer the dissolve one tick: SMODS' keep_on_use re-emplaces this
                -- card right after use() returns, so dissolving now would fight that.
                local broken = card
                G.E_MANAGER:add_event(Event({ trigger = 'after', delay = 0.15, func = function()
                    if broken and not broken.REMOVED then broken:start_dissolve() end
                    return true
                end }))
            end
        end,
    }
end
